services:
  copaco:
    build: .
    image: copaco:latest
    container_name: copaco
    ports:
      - "8000:80"
    depends_on:
      - mariadb
    networks:
      - copaco-network
    volumes:
      - ./:/var/www/html
    environment:
      HOME: /tmp
    user: "${UID:-1000}:${GID:-1000}"

  mariadb:
    image: mariadb:11
    container_name: copaco_mariadb
    restart: always
    environment:
      MYSQL_DATABASE: copaco
      MYSQL_USER: copaco
      MYSQL_PASSWORD: copaco
      MYSQL_ROOT_PASSWORD: copaco
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - copaco-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: copaco_phpmyadmin
    restart: always
    depends_on:
      - mariadb
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: copaco
    networks:
      - copaco-network

  selenium:
    image: selenium/standalone-chrome
    container_name: copaco_selenium
    ports:
      - "7900:7900"
    networks:
      - copaco-network
    shm_size: 2gb

  # No /etc/hosts do seu computador colocar a linha `127.0.0.1 auth.local`
  # particularidades do protocolo oAuth1 usado na USP
  senhaunica-faker:
    image: uspdev/senhaunica-faker
    container_name: copaco_senhaunica-faker
    ports:
      - "3141:3141"
    environment:
          - APP_URL=http://auth.local:3141
    networks:
      copaco-network:
        aliases:
          - auth.local

networks:
  copaco-network:

volumes:
  mariadb_data:
